name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout-repo
          uses: actions/checkout@v4 

        - name: List repo files
          run: ls -ltra

        - name: Executing shell Script
          run: |
               chmod +x /Users/phanikumarkaryabhattu/Github actions/githubaction/.github/workflows/shellscript.sh
               ./shellscript.sh

         


      

     
          
